### ISSUE TITLE
Windows build

### ISSUE THREAD

**Issue by h-vetinari** [conda-forge/atari_py-feedstock#3]
I saw that @oblute already tried to build for windows in conda-forge/staged-recipes#11195, and that this is apparently not considered supported upstream, but I wanted to add this issue to track it at least.

**Comment by h-vetinari** [comment]
@oblute, coming back to this due to https://github.com/conda-forge/staged-recipes/pull/11160:
Have just looked [upstream](https://github.com/openai/atari-py), they do say
> We also have binaries for Windows, but compiling from source on Windows or using the binaries is not officially supported.

Presumably, that's being done with: https://github.com/openai/atari-py/blob/master/win_build.sh

CC @vnlitvinov

**Comment by vnlitvinov** [comment]
That file looks more like a sketch which should be translated into conda-build speak, I don't think it could be used as-is.
